# UNSGML program (c) Gregory Grefenstette
# This program is licensed under a Creative Commons Attribution 4.0 International License.
# You should have received a copy of the license along with this
# work.  If not, see <http://creativecommons.org/licenses/by/4.0/>.

/[&]/ {gsub("[&]ast;","\*");
gsub("[&]equals;","\=");
gsub("[&]percnt;","\%");
gsub("[&]plus;","\+");
gsub("[&]sol;","\/");
gsub("[&]half;","\xbd");
gsub("[&]horbar;"," horbar ");
gsub("[&]lowbar;","\_");
gsub("[&]dash;"," dash ");
gsub("[&]Aacute;","\xc1");
gsub("[&]aacute;","\xe1");
gsub("[&]abreve;"," abreve ");
gsub("[&]Acirc;","\xc2");
gsub("[&]acirc;","\xe2");
gsub("[&]acute;","\xb4");
gsub("[&]AElig;","\xc6");
gsub("[&]aelig;","\xe6");
gsub("[&]agr;"," agr ");
gsub("[&]Agrave;","\xc0");
gsub("[&]agrave;","\xe0");
gsub("[&]Amacr;"," Amacr ");
gsub("[&]amacr;"," amacr ");
gsub("[&]amp;","\&");
gsub("[&]ape;"," ape ");
gsub("[&]aogon;"," aogon ");
gsub("[&]Aring;","\xc5");
gsub("[&]aring;","\xe5");
gsub("[&]atilde;","\xe3");
gsub("[&]Auml;","\xc4");
gsub("[&]auml;","\xe4");
gsub("[&]Bgr;"," Bgr ");
gsub("[&]bgr;"," bgr ");
gsub("[&]bquo;","\x60");
gsub("[&]bsol;","\x5c");
gsub("[&]bull;"," bull ");
gsub("[&]cacute;"," cacute ");
gsub("[&]Ccaron;"," Ccaron ");
gsub("[&]ccaron;"," ccaron ");
gsub("[&]Ccedil;","\xc7");
gsub("[&]ccedil;","\xe7");
gsub("[&]ccirc;"," ccirc ");
gsub("[&]cent;","\xa2");
gsub("[&]check;"," check ");
gsub("[&]cir;"," cir ");
gsub("[&]circ;","\x5e");
gsub("[&]commat;","\@");
gsub("[&]copy;","\xa9");
gsub("[&]darr;"," darr ");
gsub("[&]dcaron;"," dcaron ");
gsub("[&]deg;","\xb0");
gsub("[&]Dgr;"," Dgr ");
gsub("[&]dgr;"," dgr ");
gsub("[&]die;","\xa8");
gsub("[&]divide;","\xf7");
gsub("[&]dollar;","\x24");
gsub("[&]dstrok;"," dstrok ");
gsub("[&]dtrif;"," dtrif ");
gsub("[&]Eacute;","\xc9");
gsub("[&]eacute;","\xe9");
gsub("[&]Ecaron;"," Ecaron ");
gsub("[&]ecaron;"," ecaron ");
gsub("[&]Ecirc;","\xca");
gsub("[&]ecirc;","\xea");
gsub("[&]eegr;"," eegr ");
gsub("[&]Egr;"," Egr ");
gsub("[&]egr;"," egr ");
gsub("[&]Egrave;","\xc8");
gsub("[&]egrave;","\xe8");
gsub("[&]Emacr;"," Emacr ");
gsub("[&]emacr;"," emacr ");
gsub("[&]eogon;"," eogon ");
gsub("[&]equo;","\"");
gsub("[&]eth;","\xf0");
gsub("[&]Euml;","\xcb");
gsub("[&]euml;","\xeb");
gsub("[&]flat;"," flat ");
gsub("[&]formula;"," formula ");
gsub("[&]frac12;","\xbd");
gsub("[&]frac13;"," frac ");
gsub("[&]frac14;","\xbc");
gsub("[&]frac15;"," frac ");
gsub("[&]frac16;"," frac ");
gsub("[&]frac17;"," frac ");
gsub("[&]frac18;"," frac ");
gsub("[&]frac19;"," frac ");
gsub("[&]frac23;"," frac ");
gsub("[&]frac25;"," frac ");
gsub("[&]frac34;","\xbe");
gsub("[&]frac35;"," frac ");
gsub("[&]frac38;"," frac ");
gsub("[&]frac45;"," frac ");
gsub("[&]frac47;"," frac ");
gsub("[&]frac56;"," frac ");
gsub("[&]frac58;"," frac ");
gsub("[&]frac78;"," frac ");
gsub("[&]ft;","\'");
gsub("[&]ge;"," ge ");
gsub("[&]Ggr;"," Ggr ");
gsub("[&]ggr;"," ggr ");
gsub("[&]grave;","\x60");
gsub("[&]gt;","\>");
gsub("[&]Gt;"," Gt ");
gsub("[&]hearts;"," hearts ");
gsub("[&]hellip;"," hellip ");
gsub("[&]hstrok;"," hstrok ");
gsub("[&]Iacute;","\xcd");
gsub("[&]iacute;","\xed");
gsub("[&]Icirc;","\xce");
gsub("[&]icirc;","\xee");
gsub("[&]iexcl;","\xa1");
gsub("[&]igr;"," igr ");
gsub("[&]igrave;","\xec");
gsub("[&]imacr;"," imacr ");
gsub("[&]infin;"," infin ");
gsub("[&]ins;","\"");
gsub("[&]iquest;","\xbf");
gsub("[&]Iuml;","\xcf");
gsub("[&]iuml;","\xef");
gsub("[&]kgr;"," kgr ");
gsub("[&]khgr;"," khgr ");
gsub("[&]Lacute;"," Lacute ");
gsub("[&]lacute;"," lacute ");
gsub("[&]larr;"," larr ");
gsub("[&]lcub;","\{");
gsub("[&]le;"," le ");
gsub("[&]lgr;"," lgr ");
gsub("[&]lsqb;","\[");
gsub("[&]Lstrok;"," Lstrok ");
gsub("[&]lstrok;"," lstrok ");
gsub("[&]lt;","\<");
gsub("[&]Lt;"," Lt ");
gsub("[&]mdash;"," - ");
gsub("[&]Mgr;"," Mgr ");
gsub("[&]mgr;"," mgr ");
gsub("[&]micro;","\xb5");
gsub("[&]middot;","\xb7");
gsub("[&]nacute;"," nacute ");
gsub("[&]natur;"," natur ");
gsub("[&]ncaron;"," ncaron ");
gsub("[&]ncedil;"," ncedil ");
gsub("[&]ndash;"," ndash ");
gsub("[&]ngr;"," ngr ");
gsub("[&]Ntilde;","\xd1");
gsub("[&]ntilde;","\xf1");
gsub("[&]num;","\#");
gsub("[&]Oacute;","\xd3");
gsub("[&]oacute;","\xf3");
gsub("[&]Ocirc;","\xd4");
gsub("[&]ocirc;","\xf4");
gsub("[&]OElig;"," OElig ");
gsub("[&]oelig;"," oelig ");
gsub("[&]Ogr;"," Ogr ");
gsub("[&]ogr;"," ogr ");
gsub("[&]ograve;","\xf2");
gsub("[&]OHgr;"," OHgr ");
gsub("[&]ohgr;"," ohgr ");
gsub("[&]ohm;"," ohm ");
gsub("[&]omacr;"," omacr ");
gsub("[&]Oslash;","\xd8");
gsub("[&]oslash;","\xf8");
gsub("[&]Otilde;","\xd5");
gsub("[&]otilde;","\xf5");
gsub("[&]Ouml;","\xd6");
gsub("[&]ouml;","\xf6");
gsub("[&]Pgr;"," Pgr ");
gsub("[&]pgr;"," pgr ");
gsub("[&]PHgr;"," PHgr ");
gsub("[&]phgr;"," phgr ");
gsub("[&]plusmn;","\xb1");
gsub("[&]pound;?;","\xa3");
gsub("[&]Prime;"," Prime ");
gsub("[&]prime;"," prime ");
gsub("[&]PSgr;"," PSgr ");
gsub("[&]psgr;"," psgr ");
gsub("[&]quot;","\"");
gsub("[&]racute;"," racute ");
gsub("[&]radic;"," radic ");
gsub("[&]rarr;"," rarr ");
gsub("[&]Rcaron;"," Rcaron ");
gsub("[&]rcaron;"," rcaron ");
gsub("[&]rcub;","\}");
gsub("[&]reg;","\xae");
gsub("[&]rehy;","\xad");
gsub("[&]rgr;"," rgr ");
gsub("[&]rsqb;","\]");
gsub("[&]Sacute;"," Sacute ");
gsub("[&]sacute;"," sacute ");
gsub("[&]Scaron;"," Scaron ");
gsub("[&]scaron;"," scaron ");
gsub("[&]Scedil;"," Scedil ");
gsub("[&]scedil;"," scedil ");
gsub("[&]scirc;"," scirc ");
gsub("[&]sect;","\xa7");
gsub("[&]Sgr;"," Sgr ");
gsub("[&]sgr;"," sgr ");
gsub("[&]sharp;"," sharp ");
gsub("[&]sim;"," sim ");
gsub("[&]shilling;","  ");
gsub("[&]sup1;","\xb9");
gsub("[&]sup2;","\xb2");
gsub("[&]sup3;","\xb3");
gsub("[&]szlig;","\xdf");
gsub("[&]tcaron;"," tcaron ");
gsub("[&]tcedil;"," tcedil ");
gsub("[&]tgr;"," tgr ");
gsub("[&]THgr;"," THgr ");
gsub("[&]thgr;"," thgr ");
gsub("[&]THORN;","\xde");
gsub("[&]thorn;","\xfe");
gsub("[&]tilde;","\x7e");
gsub("[&]times;","\xd7");
gsub("[&]trade;"," trade ");
gsub("[&]Uacute;","\xda");
gsub("[&]uacute;","\xfa");
gsub("[&]Ucirc;","\xdb");
gsub("[&]ucirc;","\xfb");
gsub("[&]Ugr;"," Ugr ");
gsub("[&]ugr;"," ugr ");
gsub("[&]ugrave;","\xf9");
gsub("[&]umacr;"," umacr ");
gsub("[&]uml;","\xa8");
gsub("[&]uring;"," uring ");
gsub("[&]Uuml;","\xdc");
gsub("[&]uuml;","\xfc");
gsub("[&]verbar;","\|");
gsub("[&]wcirc;"," wcirc ");
gsub("[&]xgr;"," xgr ");
gsub("[&]yacute;","\xfd");
gsub("[&]Ycirc;"," Ycirc ");
gsub("[&]ycirc;"," ycirc ");
gsub("[&]yen;","\xa5");
gsub("[&]Yuml;"," Yuml ");
gsub("[&]yuml;","\xff");
gsub("[&]zacute;"," zacute ");
gsub("[&]Zcaron;"," Zcaron ");
gsub("[&]zcaron;"," zcaron ");
gsub("[&]zdot;"," zdot ");
gsub("[&]Zgr;"," Zgr ");
gsub("[&]zgr;"," zgr ");
   }
{ print }
